import type { Unit } from "@tot-opos/types";

export const units: Unit[] = [
  // ─── Rama genérica ──────────────────────────────────────────────────────────
  {
    id: "root-generic",
    name: "Temario General de Oposiciones",
    parentId: null,
    type: "raiz",
    order: 1,
  },

  // Bloque I — Constitución
  {
    id: "bloque-constitucion",
    name: "Bloque I: Constitución Española",
    parentId: "root-generic",
    type: "bloque",
    order: 1,
  },
  {
    id: "tema-1",
    name: "Tema 1: La Constitución Española de 1978",
    parentId: "bloque-constitucion",
    type: "tema",
    order: 1,
  },
  {
    id: "tema-1-1",
    name: "Subtema 1.1: Estructura y principios",
    parentId: "tema-1",
    type: "subtema",
    order: 1,
  },
  {
    id: "tema-1-2",
    name: "Subtema 1.2: Derechos y libertades fundamentales",
    parentId: "tema-1",
    type: "subtema",
    order: 2,
  },
  {
    id: "tema-2",
    name: "Tema 2: La Corona y las Cortes Generales",
    parentId: "bloque-constitucion",
    type: "tema",
    order: 2,
  },
  {
    id: "tema-3",
    name: "Tema 3: El Gobierno y la Administración del Estado",
    parentId: "bloque-constitucion",
    type: "tema",
    order: 3,
  },

  // Bloque II — Procedimiento Administrativo
  {
    id: "bloque-procedimiento",
    name: "Bloque II: Procedimiento Administrativo",
    parentId: "root-generic",
    type: "bloque",
    order: 2,
  },
  {
    id: "tema-4",
    name: "Tema 4: La Ley 39/2015 de Procedimiento Administrativo Común",
    parentId: "bloque-procedimiento",
    type: "tema",
    order: 1,
  },
  {
    id: "tema-4-1",
    name: "Subtema 4.1: Los interesados y la representación",
    parentId: "tema-4",
    type: "subtema",
    order: 1,
  },
  {
    id: "tema-4-2",
    name: "Subtema 4.2: El acto administrativo",
    parentId: "tema-4",
    type: "subtema",
    order: 2,
  },
  {
    id: "tema-5",
    name: "Tema 5: Recursos administrativos",
    parentId: "bloque-procedimiento",
    type: "tema",
    order: 2,
  },
  {
    id: "tema-6",
    name: "Tema 6: La responsabilidad patrimonial de la Administración",
    parentId: "bloque-procedimiento",
    type: "tema",
    order: 3,
  },

  // Bloque III — Régimen Local
  {
    id: "bloque-regimen-local",
    name: "Bloque III: Régimen Local",
    parentId: "root-generic",
    type: "bloque",
    order: 3,
  },
  {
    id: "tema-7",
    name: "Tema 7: La Administración Local. El municipio",
    parentId: "bloque-regimen-local",
    type: "tema",
    order: 1,
  },
  {
    id: "tema-8",
    name: "Tema 8: Organización municipal",
    parentId: "bloque-regimen-local",
    type: "tema",
    order: 2,
  },
  {
    id: "tema-9",
    name: "Tema 9: Las competencias municipales y la hacienda local",
    parentId: "bloque-regimen-local",
    type: "tema",
    order: 3,
  },

  // ─── Rama específica: Ajuntament de Barcelona ────────────────────────────────
  {
    id: "root-bcn",
    name: "Ajuntament de Barcelona",
    parentId: null,
    type: "raiz",
    order: 2,
  },
  {
    id: "bcn-auxiliar",
    name: "Auxiliar Administratiu",
    parentId: "root-bcn",
    type: "categoria",
    order: 1,
  },
  {
    id: "bcn-t1",
    name: "Tema 1: La Constitució espanyola de 1978. Principis general. Drets i deures fonamentals dels espanyols. Garanties constitucionals. El Govern i l'Administració de l'Estat. El poder legislatiu. El poder judicial. Organització territorial de l'Estat.",
    parentId: "bcn-auxiliar",
    type: "tema",
    order: 1,
  },
  {
    id: "bcn-t2",
    name: "Tema 2: L'Estatut d'autonomia de Catalunya.",
    parentId: "bcn-auxiliar",
    type: "tema",
    order: 2,
  },
  {
    id: "bcn-t3",
    name: "Tema 3: L'organització municipal: el règim especial del municipi de Barcelona. L'organització política (Consell Municipal, les Comissions del Consell Municipal, Comissió de Govern, l'alcalde/essa, tinents d'alcalde, els/les regidors/es, la Junta de Portaveus) i l'organització executiva. La descentralització territorial: Els districtes. Organismes autònoms i entitats públiques empresarials. Societats mercantils i fundacions públiques. La Carta Municipal.",
    parentId: "bcn-auxiliar",
    type: "tema",
    order: 3,
  },
  {
    id: "bcn-t4",
    name: "Tema 4: L'estructura del procediment administratiu: iniciació, ordenació, instrucció i finalització. Els terminis administratius: regulació.",
    parentId: "bcn-auxiliar",
    type: "tema",
    order: 4,
  },
  {
    id: "bcn-t5",
    name: "Tema 5: L'acte administratiu: concepte i classes. Elements de l'acte administratiu. Requisits dels actes administratius. L'eficàcia dels actes. Nul·litat i anul·labilitat. El silenci administratiu. Revisió d'ofici. Recursos administratius.",
    parentId: "bcn-auxiliar",
    type: "tema",
    order: 5,
  },
  {
    id: "bcn-t6",
    name: "Tema 6: Els tributs i taxes municipals. Concepte. Referència als principals tributs municipals (especialment impost sobre béns immobles, impost sobre activitats econòmiques, impost sobre vehicles de tracció mecànica, impost sobre l'increment de valor dels terrenys de naturalesa urbana).",
    parentId: "bcn-auxiliar",
    type: "tema",
    order: 6,
  },
  {
    id: "bcn-t7",
    name: "Tema 7: Les formes d'activitat administrativa de les entitats locals. L'activitat de foment: especial referència a les subvencions. Les llicències i autoritzacions administratives: classes. La declaració responsable i la comunicació prèvia.",
    parentId: "bcn-auxiliar",
    type: "tema",
    order: 7,
  },
  {
    id: "bcn-t8",
    name: "Tema 8: El Pla d'igualtat d'oportunitats entre dones i homes vigent de l'Ajuntament de Barcelona. Drets a les persones LGTBI (Article 3 i Disposició final setzena de la Llei 4/2023, de 28 de febrer, per a la igualtat real i efectiva de les persones trans i per a la garantia dels drets a les persones LGTBI).",
    parentId: "bcn-auxiliar",
    type: "tema",
    order: 8,
  },
  {
    id: "bcn-t9",
    name: "Tema 9: La protecció de dades de caràcter personal. El règim jurídic de la protecció de dades de caràcter personal. Drets, deures i garanties derivades del règim jurídic de la protecció de dades de caràcter personal. Dret d'accés als serveis públics i a la informació pública.",
    parentId: "bcn-auxiliar",
    type: "tema",
    order: 9,
  },
  {
    id: "bcn-t10",
    name: "Tema 10: El règim jurídic de la funció pública espanyola. Les bases del règim estatutari dels funcionaris públics: l'Estatut bàsic de l'empleat públic (TREBEP). El personal al servei de les administracions públiques. Drets i deures dels funcionaris públics. Règim d'incompatibilitats del personal al servei de les administracions públiques. Règim disciplinari.",
    parentId: "bcn-auxiliar",
    type: "tema",
    order: 10,
  },
  {
    id: "bcn-t11",
    name: "Tema 11: L'accés a l'ocupació pública. L'oferta pública d'ocupació. La selecció de personal: sistemes de selecció, requisits de participació i procediment selectiu. La selecció del personal interí. La promoció interna. Mobilitat i sistemes de provisió de llocs de treball. La carrera professional. Les situacions administratives.",
    parentId: "bcn-auxiliar",
    type: "tema",
    order: 11,
  },
  {
    id: "bcn-t12",
    name: "Tema 12: Recepció i registre de documents. Organització dels documents administratius. Arxivament de documents. Conservació i eliminació de documents: avaluació i tria. Gestió dels documents electrònics. Identificació, certificació digital i signatura electrònica.",
    parentId: "bcn-auxiliar",
    type: "tema",
    order: 12,
  },
  {
    id: "bcn-t13",
    name: "Tema 13: Documentació administrativa: estructura i criteris de redacció de la carta, el certificat, la citació la diligència, la notificació i la sol·licitud. Els usos no sexistes ni discriminatoris de la llengua en el llenguatge administratiu.",
    parentId: "bcn-auxiliar",
    type: "tema",
    order: 13,
  },
  {
    id: "bcn-t14",
    name: "Tema 14: L'atenció a la ciutadania a l'Ajuntament de Barcelona, els canals de comunicació: presencials, telefònics, en línia. El web de l'Ajuntament de Barcelona. La carta de serveis d'atenció a la ciutadania. La Seu electrònica i punt d'accés general electrònic. Oficina virtual de tràmits. Tràmits telemàtics.",
    parentId: "bcn-auxiliar",
    type: "tema",
    order: 14,
  },
  {
    id: "bcn-t15",
    name: "Tema 15: Barcelona ciutat de la cultura: museus i biblioteques. Les festes tradicionals de la ciutat.",
    parentId: "bcn-auxiliar",
    type: "tema",
    order: 15,
  },
  {
    id: "bcn-t16",
    name: "Tema 16: Llei 31/1995, de 8 de novembre, de prevenció de riscos laborals: objecte, àmbit d'aplicació i definicions. Política en matèria de prevenció de riscos per protegir la seguretat i la salut en el treball. Drets i obligacions. Consulta i participació del personal.",
    parentId: "bcn-auxiliar",
    type: "tema",
    order: 16,
  },
  {
    id: "bcn-t17",
    name: "Tema 17: Word Microsoft Office: Treball amb documents, millora i revisió. Formats de text i de pàgina. Notes, numeració i vinyetes. Tabulacions. Estils i temes. Revisió ortogràfics.",
    parentId: "bcn-auxiliar",
    type: "tema",
    order: 17,
  },
  {
    id: "bcn-t18",
    name: "Tema 18: Word Microsoft Office: Taules. Imatges. Elements gràfics. Formularis. Plantilles. Impressió de documents.",
    parentId: "bcn-auxiliar",
    type: "tema",
    order: 18,
  },
  {
    id: "bcn-t19",
    name: "Tema 19: Excel Microsoft Office: Creació i edició de fulls de càlcul. Aplicació de formats a les dades. Operacions amb full de càlcul. Introducció de dades. Aplicació formats i formats avançats.",
    parentId: "bcn-auxiliar",
    type: "tema",
    order: 19,
  },
  {
    id: "bcn-t20",
    name: "Tema 20: Excel Microsoft Office: Funcions. Gràfics. Plantilles. Bases de dades. Taules dinàmiques. Protecció de dades. Impressió.",
    parentId: "bcn-auxiliar",
    type: "tema",
    order: 20,
  },
];
